# Generated by Django 2.2.5 on 2020-02-13 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import easy_thumbnails.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to=utils.models.image_path, verbose_name='Image')),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'search request',
                'verbose_name_plural': 'search requests',
            },
        ),
    ]
