# Generated by Django 2.2.5 on 2020-02-13 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200213_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequest',
            name='result',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, default=list, size=None),
        ),
    ]
