# Generated by Django 2.2.5 on 2020-02-13 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_auto_20200212_0810'),
        ('activity', '0003_auto_20200213_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='result',
        ),
        migrations.CreateModel(
            name='SearchProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_products', to='catalogue.ProductImage', verbose_name='product')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_products', to='activity.SearchRequest', verbose_name='search request')),
            ],
            options={
                'verbose_name': 'search product',
                'verbose_name_plural': 'search products',
            },
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='products',
            field=models.ManyToManyField(through='activity.SearchProduct', to='catalogue.ProductImage', verbose_name='products'),
        ),
    ]
