version: '2.3'
services:
  # PostgreSQL database
  db:
    image: postgres:9.5
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5438:5432"
  redis:
    image: redis:2.8.23
    ports:
      - "6379:6379"
  worker:
    build: .
    command: ./run_celery.sh
    environment:
      - SETTINGS_CONFIGURATION=local
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_PASSWORD=postgres

    volumes:
      - .:/code
    links:
      - db
      - redis
  img_search:
    build: .
    command: /bin/bash -c "./manage.py runserver 0.0.0.0:8000"
    environment:
      - SETTINGS_CONFIGURATION=local
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_PASSWORD=postgres
      - CUDA_VISIBLE_DEVICES=2
      - TF_CPP_MIN_LOG_LEVEL=2
    depends_on:
      - db
#      - redis
#      - worker
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    runtime: nvidia
#   image: nvidia/cuda:10.2-base-ubuntu18.04
