# Generated by Django 2.2.5 on 2020-02-12 08:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_learningconfighdf5'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('super_category', models.CharField(max_length=255, verbose_name='Super category')),
                ('vectors', models.FileField(upload_to=utils.models.vector_path, verbose_name='Vectors')),
                ('filename_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=None, null=True, size=None, verbose_name='Filename list')),
                ('article_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=None, null=True, size=None, verbose_name='Article list')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
