# Generated by Django 2.1.7 on 2019-03-23 11:33

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('article', models.CharField(max_length=512, verbose_name='Article')),
                ('image', models.ImageField(upload_to=utils.models.image_path, verbose_name='Image')),
                ('vector', models.TextField(blank=True, default=None, null=True, verbose_name='Vector')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
    ]
