# Generated by Django 2.1.7 on 2019-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='external_url',
            field=models.URLField(default=None, null=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='article',
            field=models.CharField(max_length=512, unique=True, verbose_name='Article'),
        ),
    ]
