# Generated by Django 2.2.5 on 2020-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20190921_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='error',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
