# Generated by Django 2.2.5 on 2020-02-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_productimage_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='super_category',
            field=models.CharField(choices=[('computer_chair', 'computer chair'), ('armchair_ottoman', 'armchair ottoman'), ('sofa_bed_chair', 'sofa bed chair'), ('table', 'table'), ('chair', 'chair'), ('cabinet', 'cabinet'), ('other', 'other')], default='other', max_length=255, verbose_name='super category'),
        ),
    ]
