# Generated by Django 2.2.5 on 2020-02-12 08:10

from django.db import migrations, models
import easy_thumbnails.fields
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_category_super_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, null=True, upload_to=utils.models.image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not loaded'), (1, 'Loaded'), (3, 'Not found'), (4, 'Bad format')], default=0),
        ),
    ]
